"""Per-genre description templates and word banks.

Each genre supplies:
- 4+ sentence templates using {protagonist}, {setting}, {conflict}, {theme}, {object}
- word banks for each slot

Descriptions are joined from 3 sentence templates → coherent, LLM-searchable text
without Faker filler.
"""
from __future__ import annotations

# fmt: off
GENRE_BANKS: dict[str, dict[str, list[str]]] = {
    "Fantasy": {
        "protagonist": ["a young apprentice mage", "a reluctant princess", "a wandering swordsman",
                        "a half-elf ranger", "an exiled prince", "a dragon-touched orphan"],
        "setting": ["the shattered kingdom of Vareth", "an ancient forest older than the gods",
                    "the floating citadel of Aureon", "a cursed borderland", "the ruined empire beyond the Silver Sea"],
        "conflict": ["an awakening dark sorcerer", "a broken prophecy", "the return of the old dragons",
                     "a war between rival guilds of magic", "an artifact that must never be found"],
        "theme": ["destiny and free will", "the cost of magic", "loyalty and betrayal",
                  "sacrifice for a fading world", "the price of a crown"],
        "object": ["a shard of the sunblade", "an obsidian crown", "a map drawn in blood",
                   "a talking familiar", "a forbidden tome"],
    },
    "Sci-Fi": {
        "protagonist": ["a burned-out xenoarchaeologist", "an AI awakening to consciousness",
                        "a courier pilot on the Kepler run", "a terraforming engineer",
                        "a war orphan turned station mechanic"],
        "setting": ["the Europa colonies", "a generation ship halfway through its 900-year voyage",
                    "the neutral zone around Proxima Centauri", "a post-collapse Earth",
                    "the far side of a Dyson swarm"],
        "conflict": ["a first-contact protocol going wrong", "an AI singularity event",
                     "corporate war over jump-drive patents", "a plague no one can vaccinate",
                     "a rogue faction on Titan"],
        "theme": ["what makes a person a person", "the ethics of terraforming",
                  "solitude across light-years", "the memory of a lost Earth",
                  "trust between species"],
        "object": ["a black-box quantum core", "a stolen jump manifold",
                   "an alien signal repeating on a prime cycle", "a smuggled seed vault",
                   "a neural graft"],
    },
    "Mystery": {
        "protagonist": ["a disgraced detective", "an amateur sleuth in a small coastal town",
                        "a forensic accountant", "a widowed journalist",
                        "a retired inspector called back for one last case"],
        "setting": ["a foggy port town in Maine", "an isolated Alpine hotel",
                    "the shabby edges of London's financial district", "a decaying rural county",
                    "a lakeside estate closed for the season"],
        "conflict": ["a missing heir", "a series of impossible thefts",
                     "a decades-old cold case reopening", "a suspicious death dismissed as suicide",
                     "a witness who vanishes before trial"],
        "theme": ["truth buried under respectability", "the weight of small-town silence",
                  "obsession versus justice", "grief and closure", "the lie families keep"],
        "object": ["a locked diary", "a single unmatched glove", "an unlisted phone number",
                   "a stolen ledger", "a photograph nobody remembers taking"],
    },
    "Romance": {
        "protagonist": ["a career-driven pastry chef", "a widowed architect", "an heiress in disguise",
                        "a bookshop owner", "a single-parent veterinarian"],
        "setting": ["a windswept coastal cottage", "a small-town bakery", "a Tuscan vineyard",
                    "a boutique hotel in Edinburgh", "a Manhattan brownstone"],
        "conflict": ["a former rival returning after ten years", "a family feud they must resolve together",
                     "a competing bid on their dream property", "a shared secret from college",
                     "a promise made and broken"],
        "theme": ["second chances", "opening up after loss", "trust after betrayal",
                  "finding home in another person", "risking everything for love"],
        "object": ["a shared recipe box", "a hand-written letter never sent",
                   "an engagement ring hidden in a drawer", "a Polaroid from that summer",
                   "a scarf they both remember"],
    },
    "Thriller": {
        "protagonist": ["a burned CIA analyst", "a private security contractor",
                        "an investigative reporter", "a rogue FBI agent",
                        "a cybersecurity researcher"],
        "setting": ["a shadow network stretching from Berlin to Istanbul",
                    "the underbelly of a shipping conglomerate", "a border town in the Sonora",
                    "a Washington think tank", "a hollowed-out mountain complex"],
        "conflict": ["a leaked kill list", "an assassination staged as a suicide",
                     "a mole inside the agency", "a bio-weapon smuggled across three continents",
                     "a hostage taken to force a testimony"],
        "theme": ["patriotism and its cost", "the moral weight of pulling the trigger",
                  "how far one goes to protect the innocent", "loyalty when everyone lies",
                  "the impossibility of walking away"],
        "object": ["an encrypted phone", "a numbered Swiss ledger", "a stolen dossier",
                   "a photograph the target was never supposed to see", "a dead-drop USB"],
    },
    "Horror": {
        "protagonist": ["a folklorist researching regional legends", "a family newly moved to an old farmhouse",
                        "a night-shift nurse", "a documentary filmmaker",
                        "a caretaker at a shuttered summer camp"],
        "setting": ["a New England town everyone left in 1953", "an abandoned sanatorium",
                    "a lake with a name nobody says out loud", "a fog-drowned island",
                    "a corn belt farmhouse ten miles from the nearest neighbor"],
        "conflict": ["a presence answering to old names", "children hearing voices from the walls",
                     "a ritual the town pretends it never performed", "a photograph that changes",
                     "the dead who will not stay buried"],
        "theme": ["grief that opens a door", "the sins a community buries",
                  "isolation as a slow suffocation", "how a house learns you",
                  "faith stretched past breaking"],
        "object": ["a music box that plays on its own", "a well nobody covered properly",
                   "a mirror facing another mirror", "a page torn from a parish register",
                   "a doll wearing the wrong dress"],
    },
    "Biography": {
        "protagonist": ["a jazz pioneer", "a Cold War physicist", "a suffragette leader",
                        "a Silicon Valley founder", "a wartime nurse"],
        "setting": ["mid-century New York", "post-war Vienna", "the American South during the 1960s",
                    "1990s Palo Alto", "London during the Blitz"],
        "conflict": ["public triumph shadowed by private grief",
                     "a career built and rebuilt through repeated setbacks",
                     "a battle with the era's prejudices",
                     "a decision that ended one life and started another",
                     "a rivalry that defined a generation"],
        "theme": ["ambition and its cost", "the shaping of a public figure",
                  "invisible labor behind visible fame", "the making of a movement",
                  "the loneliness of leading"],
        "object": ["an unpublished journal", "a much-cited photograph",
                   "the family Bible with dates in the margins",
                   "letters to a lifelong correspondent", "a battered first passport"],
    },
    "History": {
        "protagonist": ["a Byzantine emissary", "a colonial-era surveyor",
                        "a Renaissance banker", "an anonymous soldier",
                        "a merchant on the Silk Road"],
        "setting": ["11th-century Constantinople", "the Spanish Netherlands",
                    "Meiji Japan", "revolutionary Paris", "Ottoman Damascus"],
        "conflict": ["a shifting alliance that reshapes a century",
                     "an economic crisis with global reach",
                     "a war fought over a border no map agrees on",
                     "a religious schism", "a plague that redraws the map"],
        "theme": ["how power outlives its holders", "trade as the true engine of change",
                  "the myths nations tell themselves", "the small people history forgets",
                  "the accident behind every so-called inevitability"],
        "object": ["a treaty draft with three signatures crossed out",
                   "a coin found in an unlikely place", "a merchant ledger",
                   "a captured battle standard", "a decree read from a balcony"],
    },
    "Self-Help": {
        "protagonist": ["the reader", "the ambitious professional", "the burned-out parent",
                        "the mid-career switcher", "anyone stuck at the same milestone twice"],
        "setting": ["work you no longer recognize", "the middle of a life you did not plan",
                    "a routine you built and now resent", "a stalled creative practice",
                    "the years after the promotion"],
        "conflict": ["the story you keep telling yourself",
                     "the difference between busy and productive",
                     "the invisible rules that shape your week",
                     "avoidance dressed as ambition",
                     "goals you inherited instead of chose"],
        "theme": ["clarity over motivation", "identity behind habit",
                  "systems that outlast willpower", "boundaries as a form of self-respect",
                  "progress without perfectionism"],
        "object": ["a weekly review template", "a two-page life plan",
                   "a habit journal", "a values-first calendar",
                   "a single question that reshapes your priorities"],
    },
    "Children's": {
        "protagonist": ["a curious young fox", "a shy little robot",
                        "a girl with a magical backpack", "twin siblings",
                        "a friendly cloud named Pip"],
        "setting": ["the meadow behind the bakery", "the moon on a Saturday night",
                    "a treehouse city", "grandma's attic",
                    "the biggest library any child has ever seen"],
        "conflict": ["a lost balloon", "a friend who moved away",
                     "a birthday that almost gets forgotten",
                     "a puzzle the grown-ups can't solve",
                     "a shadow that turns out to be shy"],
        "theme": ["kindness matters", "brave is a small word for big feelings",
                  "sharing is the best kind of magic",
                  "everyone belongs somewhere",
                  "questions are the beginning of adventures"],
        "object": ["a jar of stars", "a talking teacup",
                   "a paper airplane that always comes home", "a tiny golden key",
                   "a hat two sizes too big"],
    },
    "Technical": {
        "protagonist": ["the working software engineer", "a platform team lead",
                        "an SRE on the on-call rotation", "an ML practitioner",
                        "a backend developer scaling past their first million users"],
        "setting": ["a production system under real load", "a growing microservices estate",
                    "a legacy codebase you inherited", "a distributed database at scale",
                    "a Kubernetes cluster you have to explain to auditors"],
        "conflict": ["latency that spikes only in production",
                     "a schema migration you cannot roll back",
                     "a cache invalidation that ate the weekend",
                     "a memory leak nobody can reproduce locally",
                     "an outage nobody wants to own"],
        "theme": ["observability before optimization",
                  "correctness under concurrency",
                  "the tradeoffs behind every abstraction",
                  "APIs as long-term contracts",
                  "operational maturity as a competitive edge"],
        "object": ["a runbook that actually gets read",
                   "a flamegraph that finally explains it",
                   "a canary deploy plan",
                   "a well-drawn architecture diagram",
                   "an eventually-consistent worked example"],
    },
    "Poetry": {
        "protagonist": ["the speaker", "an aging gardener", "a widow at the shoreline",
                        "a child in the last light of summer", "a translator in a foreign city"],
        "setting": ["the long edge of winter", "the room after a party ends",
                    "a station platform at dawn", "the coast at low tide",
                    "the streets where you grew up"],
        "conflict": ["a name you cannot say anymore",
                     "the small distance between love and habit",
                     "a season that refuses to end",
                     "silence sitting where a voice used to",
                     "a letter you write and never send"],
        "theme": ["memory as a kind of weather",
                  "small mercies", "language as inheritance",
                  "the ordinary made luminous",
                  "the body's slow rebellion"],
        "object": ["a chipped cup", "the scent of rain on hot stone",
                   "a photograph faded past recognition",
                   "a hand-me-down coat", "a door left slightly open"],
    },
    "Cookbook": {
        "protagonist": ["the home cook", "a self-taught baker", "a weeknight parent",
                        "a curious eater", "someone who has always been intimidated by yeast"],
        "setting": ["a small kitchen with reliable equipment",
                    "the pantry you already have", "one sheet pan and thirty minutes",
                    "a Sunday afternoon", "a farmers-market season"],
        "conflict": ["dinner in under 45 minutes",
                     "using what is already in the fridge",
                     "feeding picky eaters without a fight",
                     "cooking for one without waste",
                     "hosting without hiding in the kitchen"],
        "theme": ["technique over specialty gear",
                  "seasonality as a shortcut to flavor",
                  "the mother-sauces, updated",
                  "reading a recipe to riff on it",
                  "confidence over precision"],
        "object": ["a well-loved cast-iron pan", "a Dutch oven",
                   "a single sharp knife", "a citrus zester",
                   "a jar of house pickles"],
    },
    "Fiction": {
        "protagonist": ["a novelist between books", "an estranged sister",
                        "the last resident of a coastal town", "a returning veteran",
                        "a translator between two lives"],
        "setting": ["a small city on the edge of change",
                    "a country town nobody visits anymore",
                    "the neighborhood after the industry left",
                    "a suburb that thinks it's a village",
                    "a foreign city that never quite becomes home"],
        "conflict": ["a family secret finally landing",
                     "a homecoming nobody wanted",
                     "a friendship pulled apart by success",
                     "a marriage tested by a single sentence",
                     "an inheritance that changes everything"],
        "theme": ["the private lives inside public silences",
                  "the small distances that become oceans",
                  "class, memory, and the myths of place",
                  "the years between the decisions we don't notice",
                  "how ordinary tenderness endures"],
        "object": ["a house that keeps its own secrets",
                   "a letter arriving thirty years late",
                   "a single old photograph",
                   "a car driven all the way home",
                   "an unfinished manuscript"],
    },
    "Non-fiction": {
        "protagonist": ["the reader", "the informed citizen",
                        "the practitioner in the field", "the working professional",
                        "anyone paying attention"],
        "setting": ["a contested cultural moment",
                    "a discipline at a turning point",
                    "an industry mid-transformation",
                    "a policy landscape no one has mapped",
                    "the ground beneath the headlines"],
        "conflict": ["a debate louder than the evidence",
                     "an assumption that no longer fits the data",
                     "a movement rewriting the rules",
                     "a crisis long in the making",
                     "a story we've been telling ourselves"],
        "theme": ["evidence over consensus",
                  "the systems behind the surface",
                  "history's unfinished business",
                  "the interests hiding in plain sight",
                  "what changes when you follow the numbers"],
        "object": ["a landmark study",
                   "a decade of interviews",
                   "a single decisive chart",
                   "a whistleblower's cache of documents",
                   "a footnote that reframes the argument"],
    },
}
# fmt: on

# Three-sentence description skeletons chosen per genre. Slot names must exist
# in the corresponding word bank.
GENRE_TEMPLATES: dict[str, list[str]] = {
    "Fantasy": [
        "In {setting}, {protagonist} discovers {object} — and with it the truth about {conflict}.",
        "Between prophecy and betrayal lies a single choice, and only {protagonist} can make it.",
        "A sweeping tale of {theme}, spanning kingdoms lost and kingdoms yet to fall.",
    ],
    "Sci-Fi": [
        "When {protagonist} intercepts {object}, {conflict} becomes inevitable.",
        "Somewhere between {setting} and the next jump, humanity's future is being decided.",
        "A meditation on {theme}, at the speed of light.",
    ],
    "Mystery": [
        "When a body turns up in {setting}, {protagonist} is drawn back into a case they thought was closed.",
        "The clues point to {conflict} — but every witness has a reason to lie.",
        "A quiet, unnerving portrait of {theme}, where the smallest detail changes everything.",
    ],
    "Romance": [
        "{protagonist} never expected to see them again, least of all in {setting}.",
        "Between {conflict} and a promise neither of them made, something new begins to grow.",
        "A warm, unhurried love story about {theme}.",
    ],
    "Thriller": [
        "72 hours. {protagonist}. {conflict}. No backup.",
        "From {setting}, the trail leads somewhere no one is meant to follow.",
        "A pulse-tight examination of {theme} at the sharp edge of a career.",
    ],
    "Horror": [
        "When {protagonist} arrives in {setting}, the locals warn them not to ask about {conflict}.",
        "Something is answering. Something is listening. And it knows {object} by name.",
        "A slow, patient nightmare about {theme}.",
    ],
    "Biography": [
        "This is the definitive portrait of a life shaped by {setting} and defined by {conflict}.",
        "Drawing on {object}, the biography traces the arc from unknown beginnings to enduring influence.",
        "A rigorous, humane account of {theme}.",
    ],
    "History": [
        "In {setting}, {protagonist} stands at the center of {conflict} — a story most textbooks skip.",
        "Working from {object} and a decade of primary sources, the author reconstructs the era from the inside.",
        "A vivid, argument-driven history of {theme}.",
    ],
    "Self-Help": [
        "For {protagonist}, the problem was never {conflict} — it was the story underneath.",
        "This book offers {object} and a practical framework you can start using today.",
        "A grounded guide to {theme}, without the hustle-culture noise.",
    ],
    "Children's": [
        "Meet {protagonist}! They live in {setting}, and today is a very big day.",
        "When {conflict} happens, {protagonist} needs a little help — and {object}.",
        "A warm story about {theme}, perfect for reading aloud.",
    ],
    "Technical": [
        "For {protagonist}: a field guide to {setting} that assumes you already ship to production.",
        "Every chapter tackles {conflict} with worked examples, {object}, and lessons from real outages.",
        "The through-line is {theme}, applied to systems that actually have to stay up.",
    ],
    "Poetry": [
        "A collection returning to {setting}, and to {conflict} that never quite closes.",
        "Every poem circles {object}, patient and unhurried.",
        "The book listens for {theme}, and answers in a voice you'll want to read aloud.",
    ],
    "Cookbook": [
        "Written for {protagonist} working with {setting}, this book solves {conflict} with fewer than a dozen pantry staples.",
        "Every recipe uses {object} you already own, with weeknight timing and clear technique.",
        "The organizing idea is {theme}, so the recipes teach as they feed you.",
    ],
    "Fiction": [
        "{protagonist} returns to {setting}, and {conflict} begins the moment they arrive.",
        "The story turns on {object}, and on the questions it forces open.",
        "A quietly devastating novel about {theme}.",
    ],
    "Non-fiction": [
        "In {setting}, {protagonist} confronts {conflict} — and finds the received story doesn't hold.",
        "Built on {object}, the argument reframes what most readers think they know.",
        "The result is a clear-eyed book about {theme}.",
    ],
}
